### ISSUE TITLE
Tracking not working

### ISSUE THREAD

**Issue by MekoNix** [yagiziskirik/Kerbal-Telemetry#5]
Hi, I did everything according to the instructions. But the site does not display my rockets in orbit. After I moved the mod folder to the game data folder, start points appeared on the flight halogram. Perhaps this is due to the error that krps is showing me. dll of the MechJeb autopilot was not found. Sorry for possible grammatical errors, I use a translator and it's not always good.
kPRC error
![image](https://user-images.githubusercontent.com/64309709/114283207-3b215200-9a51-11eb-94b0-9031fd10f2ef.png)

In case you haven't noticed, the ship name is not in the KSP files. Possibly this is because of the Russian name. But after the test, I realized that this was just a mistake.
![image](https://user-images.githubusercontent.com/64309709/114283213-41afc980-9a51-11eb-9a69-a8cdde243f52.png)

But there is still a connection with your program and game. (Not sure, but as shown in the screenshot below, the program found Kerbal Telemetry)
![image](https://user-images.githubusercontent.com/64309709/114283447-7b350480-9a52-11eb-989e-da1516d4d035.png)

**Comment by yagiziskirik** [comment]
Hello @MekoNix,

Thank you for reporting this issue. You gave me a perfectly detailed report to solve. I think the problem is caused by some Russian characters in the rocket part names. I have seen this example in the Chinese too. Can you try the game in English and tell me whether it is working?

Also, kRPC is giving that error because it is haven't been updated for a while now. The reason you see a different spacecraft name on the Spacecraft part of the User Interface is probably caused by focusing on some parts which have been separated from spacecraft (for example thruster debris). Other than that, I couldn't see any potential issues. I am planning to fix all of these errors in the next update.

And thank you for writing this issue on GitHub. I return to these messages faster since GitHub sends me an email to inform me that there is an update. I saw your post on Curse Forge as well and respond to that. I will be waiting for your response.

**Comment by Genhis** [comment]
Hi, the author of kRPC.MechJeb here.

I had a similar issue reported https://github.com/Genhis/KRPC.MechJeb/issues/17 and the workaround was to downgrade MechJeb version to 2.9.2.0.

**Comment by yagiziskirik** [comment]
Hello @Genhis,

I never thought I would be able to be corrected by you, thank you for your contribution. I am updating the ReadMe files right now, you created a beautiful mod by the way.

**Comment by MekoNix** [comment]
Unfortunately, I still can't figure out the problem. Yes installation of MechJeb version 2.9.2.0. helped to get rid of errors. I installed the English version on Steam, but nothing has changed. You also pointed out that Telemetry can track debris, but in the game, there was one command squad that was sent into orbit using cheats. I also ran a test with the standard ship Kerbal X. The result does not work. I am not receiving information about my ships in orbit. Also, I don't have the starting points that I had before. It looks like the program cannot get information and shows information from the file compiled in the Russian version of the kerbal space program.
In the ReadMe, you instructed to install kRPC, but Genhis instructed to install MechJeb.

**Comment by yagiziskirik** [comment]
As far as I understood, Kerbal Telemetry is not referring to the English version of KSP right now. Can I ask you to manually reinstall the Kerbal Telemetry mod to the current KSP version that you are using? Also, there are three dependencies for *launching* the spacecraft into orbit. kRPC, MechJeb and kRPC.MechJeb. MechJeb is responsible for auto-launching the spacecraft, kRPC is responsible for controlling or getting information from KSP and kRPC.MechJeb is responsible for connecting MechJeb to kRPC. The program should be able to get information from the spacecraft without these three.

And also you are right, I made a mistake and wrote it to the wrong mod, I am fixing that right now, thank you.

**Comment by MekoNix** [comment]
Excellent. Telemetry is finally working. The solution was to reinstall the game without switching to Russian.
   Orbit does not always indicate a decision to put game data in a folder.
Ironically, after running out of fuel, the rocket attempts to use the RCS to continue its flight.
Also I cannot use buttons to control flight in the web interface.

Suggestions:
Add link to MechJeb v2.9.2.0 version
Translate the web interface into other languages. Since when using Google Translate in the browser, it cannot concentrate and shows one language then another, it gets in the way of tracking metrics a little.

![ScreenRecorderProject4_1](https://user-images.githubusercontent.com/64309709/114305633-ae72a480-9ae1-11eb-8da9-302a451a42c0.gif)
If necessary, I can translate pages into Russian and Japanese without a translator.
It's just that the phrase "Date with a point" is very funny.
Your mod is very good thank you.

**Comment by MekoNix** [comment]
I don't know what happened, but it doesn't work again. I play in the English versio. Well, I'll wait for your update to languages, I hope everything will work again. 
I will also start localizing the web interface.

**Comment by yagiziskirik** [comment]
I was very happy until the moment I saw the second comment of yours 😅

I could be able to use both Russian and Chinese on the web interface with a quick update. (Copy-pasted, I don't know Russian, sorry!)
![Screenshot](https://user-images.githubusercontent.com/33431578/114355187-d7457900-9b77-11eb-9f07-71e607556e4a.png)

Can I ask you to use this updated [telemetryserver.py](https://github.com/yagiziskirik/Kerbal-Telemetry/files/6294623/TelemetryServerNew.zip) file on the Telemetry Server folder? Remember that this is preproduction, you may encounter some additional problems as well. 

And you can try to clear the cache of the web interface. To do that, I do `Ctrl + Shift + R or opening the console, right-clicking to the reload button and click clear cache and reload. But it can change depending on your browser.

Also, I will definitely try to accomplish your suggestions and I can use some help on translating to Russian. If you are still interested, send me an email to [y_iskirik_10@hotmail.com](mailto:y_iskirik_10@hotmail.com) and I can send you the phrases which need to be translated. This can take a couple of days but I will be trying to gather all the phrases and finding a solution to change languages.

**Comment by MekoNix** [comment]
Ok I'll check out the new script soon. I will send all the information about the tests to the mailbox you specified. And so I close the question

**Comment by yagiziskirik** [comment]
Thank you @MekoNix,

I gathered all the phrases which need to be translated about an hour ago. But I needed to attend a meeting so I couldn't inform you about this. I created a Google Sheets document and wrote every single phrase to it. So far there are only 81 entries and most of them are just one or two words. I will send you the link to edit that page as soon as you contact me.
